name: 'nonguix-mirror'
on:
  push:
    branches:
        - __mirror
  schedule:
    # Run everyday at 3 AM UTC
    - cron: '1 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: bridgelightcloud/github-mirror-action@v3
        with:
          origin: 'https://gitlab.com/nonguix/nonguix.git'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
